language: node_js
node_js:
  - "10.6.0"
cache:
  directories:
    - node_modules

before_install:
  - npm prune
  - npm update

install:
  - npm install

script:
  - ng build --prod
  
deploy:
  skip_cleanup: true
  provider: script
  script: node deploy.js
  on:
    branch: stage
